# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  
      
jobs:  
  build:
    env:
      BUILD_CONFIG: Release
      VERSION_SUFFIX: -preview${{ github.run_id }}
    services:
      sql-server:
        image: microsoft/mssql-server-linux
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: Password12!
        ports:
            - 1833:1433
      postgres:
        image: postgres
        ports:
            - 8010:5432
        env:
            POSTGRES_PASSWORD: Password12!
      mysql:
        image: mysql
        ports:
            - 3306:3306
        env:
            MYSQL_ROOT_PASSWORD: Password12!
            MYSQL_USER: mysql
            MYSQL_PASSWORD: Password12! 
      mongodb:
        image: mongo
        ports:
            - 27017:27017
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v2      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore
        run: dotnet restore ./AspNetCore.Diagnostics.HealthChecks.sln
      - name: Build with dotnet
        run: dotnet build ./AspNetCore.Diagnostics.HealthChecks.sln --configuration $BUILD_CONFIG
      - name: dotnet test UnitTests
        run: dotnet test --no-build
        working-directory: ./test/UnitTests
      - name: dotnet pack
        run: dotnet pack -o ./artifacts
        working-directory: ./src -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
        
