# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  
      
jobs:  
  build:  
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v2      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore
        run: dotnet restore ./AspNetCore.Diagnostics.HealthChecks.sln
      - name: Build with dotnet
        run: dotnet build ./AspNetCore.Diagnostics.HealthChecks.sln --configuration Release
